os: linux
language: c
compiler: gcc
env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
addons:
  apt:
    packages:
      - bc
script:
- ./build_ale21.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "arch/arm64/boot/Image"
  skip_cleanup: true
  on:
    tags: true
